### PR TITLE
Jk add aside

### PR DESCRIPTION
**Pull request by jkaset**
# Description
Please check my html for aside and footer looks perfect and workable and that the dummy text is working for all the parts. Approve working skeleton.
## Type of change
- [x ] New feature (non-breaking change which adds functionality)
functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions
1. `git fetch --all`
1. `git checkout jk-add-aside`
1. `serve`
1. check html for aside and footer, look for filler text, approve working skeleton.

### CODE REVIEW

**Comment by tedmarov** [comment]
Footer structure should be separate from main, i.e.:

body | header | main | footer | body

**Comment by silaslowe** [comment]
`footer` needs to be outside the `main`

**Comment by silaslowe** [comment]
👍 Looks good!

**Comment by tedmarov** [comment]
footer should be its own tag

**Pull request closed without merging**
